### ISSUE TITLE
How can I obtain the location where reads map to TEs

### ISSUE THREAD

**Issue by CPTPaso** [LiuzLab/SalmonTE#44] opened 2020-08-14 06:38 UTC
Hi,

is there a way to check the genomic location where the TEs identified by SalmonTE are located? Then I could easily load the bams into IGV and validate SalmonTE findings and would not have to run a RT-qPCR in the first place.

Thanks for your help!

**Comment by hyunhwaj** [comment] 2020-08-14 19:40
Duplicate of #42

**Comment by hyunhwaj** [comment] 2020-08-14 19:50
Hi @CPTPaso, there a couple of ways you can lookup the potential loci:

1. Using databases like [dfam](https://dfam.org/), [RepeatMasker](http://www.repeatmasker.org/), or [RepeatBrowser](https://repeatbrowser.ucsc.edu/)
2. You can [blat](https://genome.ucsc.edu/cgi-bin/hgBlat?command=start) with the TE sequence. 
 

Please be aware that SalmonTE only quantifies overall TE abundances can't extract the exact locus. Please refer #42  - there a discussion regarding this matter. 

Best,

Hyun-Hwan Jeong

**Closed** 2020-08-15 02:59 UTC
